# Generated by Django 3.2.10 on 2024-08-08 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        ('feecategories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('frequency', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='feeextensions.paymentplan')),
            ],
        ),
        migrations.CreateModel(
            name='FeeExtensions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dueDate', models.DateField(null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_reminder_sent', models.DateField(blank=True, null=True)),
                ('reminder_frequency', models.IntegerField(default=3)),
                ('method_of_payment', models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('equity_account', 'Equity Account'), ('stripe_card', 'Stripe Card')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('lapsed', 'Lapsed')], default='pending', max_length=20)),
                ('feecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feecategories.feecategories')),
                ('school_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schools')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
                ('student_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.studentaccount')),
            ],
            options={
                'db_table': 'fee_extensions',
            },
        ),
    ]
